config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                    Controller#Action
#         new_user_session GET    /users/sign_in(.:format)       devise/sessions#new
#             user_session POST   /users/sign_in(.:format)       devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)      devise/sessions#destroy
#            user_password POST   /users/password(.:format)      devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)  devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format) devise/passwords#edit
#                          PATCH  /users/password(.:format)      devise/passwords#update
#                          PUT    /users/password(.:format)      devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)        devise/registrations#cancel
#        user_registration POST   /users(.:format)               devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)       devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)          devise/registrations#edit
#                          PATCH  /users(.:format)               devise/registrations#update
#                          PUT    /users(.:format)               devise/registrations#update
#                          DELETE /users(.:format)               devise/registrations#destroy
#                    posts GET    /posts(.:format)               posts#index
#                          POST   /posts(.:format)               posts#create
#                 new_post GET    /posts/new(.:format)           posts#new
#                edit_post GET    /posts/:id/edit(.:format)      posts#edit
#                     post GET    /posts/:id(.:format)           posts#show
#                          PATCH  /posts/:id(.:format)           posts#update
#                          PUT    /posts/:id(.:format)           posts#update
#                          DELETE /posts/:id(.:format)           posts#destroy
#             person_index GET    /person(.:format)              person#index
#                          POST   /person(.:format)              person#create
#               new_person GET    /person/new(.:format)          person#new
#              edit_person GET    /person/:id/edit(.:format)     person#edit
#                   person GET    /person/:id(.:format)          person#show
#                          PATCH  /person/:id(.:format)          person#update
#                          PUT    /person/:id(.:format)          person#update
#                          DELETE /person/:id(.:format)          person#destroy
#                    twits GET    /twits(.:format)               twits#index
#                          POST   /twits(.:format)               twits#create
#                 new_twit GET    /twits/new(.:format)           twits#new
#                edit_twit GET    /twits/:id/edit(.:format)      twits#edit
#                     twit GET    /twits/:id(.:format)           twits#show
#                          PATCH  /twits/:id(.:format)           twits#update
#                          PUT    /twits/:id(.:format)           twits#update
#                          DELETE /twits/:id(.:format)           twits#destroy
#            relationships POST   /relationships(.:format)       relationships#create
#             relationship DELETE /relationships/:id(.:format)   relationships#destroy
#                     root GET    /                              redirect(301, /person)
#

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  resources :posts
  resources :person
  resources :twits

  resources :relationships, only: [:create, :destroy]

  root :to => redirect('/person')

  match '/users/:id/finish_signup' => 'person#finish_signup', via: [:get, :patch], :as => :finish_signup
  # get '/person/:id/followers' => 'person#followers'
  # get '/person/:id/following' => 'person#following'

  # get '/followers/:id' => 'followers#index'

  match '/followers/:id' => 'followers#index', via: :get, :as => :followers
  match '/following/:id' => 'following#index', via: :get, :as => :following

end

app/controllers/person_controller.rb
class PersonController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  helper_method :following, :followers

  def show
    @user = User.find(params[:id])
    @twit = @user.twits.build if signed_in?
    @twits = @user.twits.paginate(page: params[:page])
    @host = request.host_with_port()
  end

  def index
    @host = request.host_with_port()
    if(Unity.where(user_id: current_user.id).first)
      current_user.current_role = Unity.where(user_id: current_user.id).first.role.name
    else
      current_user.current_role = ""
    end
    @user = current_user
    @twit = current_user.twits.build if signed_in?
    @twits = current_user.feed
    @twits = @twits.paginate(page: params[:page], :per_page => 2)
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @twits }
    end

  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  def finish_signup
    # authorize! :update, @user
    if request.patch? && params[:user] #&& params[:user][:email]
      if current_user.update(user_params)
        current_user.skip_reconfirmation!
        sign_in(current_user, :bypass => true)
        redirect_to root_url, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    accessible = [ :name, :email ] # extend with your own params
    accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
    params.require(:user).permit(accessible)
  end
end

app/helpers/person_helper.rb
module PersonHelper
end

app/views/person/_form.html.erb
<%= form_for(@twit) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <%= f.text_area :content, placeholder: "Compose new twit..." %>
      <div style="display:none">
        <%= f.text_area :user_id, :value => current_user.id %>
      </div>
    </div>
    <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/person/finish_signup.html.erb
<div id="add-email" class="bg move-down edit-profile">
  <h1>Add Email</h1>
  <%= form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f| %>
      <% if @show_errors && current_user.errors.any? %>
          <div id="error_explanation">
            <% current_user.errors.full_messages.each do |msg| %>
                <%= msg %><br>
            <% end %>
          </div>
      <% end %>
      <div class="form-group">
        <%= f.label :email %>
        <div class="controls">
          <%= f.text_field :email, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'Example: email@me.com' %>
          <p class="help-block">Please confirm your email address. No spam.</p>
        </div>
      </div>
      <div class="actions">
        <%= f.submit 'Continue', :class => 'btn btn-primary' %>
      </div>
  <% end %>
</div>

app/views/person/index.html.erb
<div class="move-down">
<div class="left profile">
  <div>
      <%= image_tag current_user.avatar.url(:preview) %>
    <h4>
      <%= current_user.email %>
    </h4>
    <p></p>

  </div>
  <div>

    <section>
      <%= render 'shared/stats' %>
    </section>
    <% if can? :create, Twit %>
        <section>
          <%= render 'form' %>
        </section>
    <% end %>

  </div>

  <p></p>

</div>

<div class="left">
  <div class="span8">
    <% if @twits.any? %>
          <div class="panel panel-primary">
            <div class="panel-heading">Twit Feed (<%= @twits.count %>)</div>
            <ul>
            <%= render @twits %>
          </ul>
            <div class="flickr_pagination without-markers">
              <%= will_paginate @twits, :container => false %>
            </div>

          </div>
    <% end %>
  </div>

</div>
</div>

app/views/person/show.html.erb
<div class="move-down">
<div class="left profile">
  <%= image_tag @user.avatar.url(:preview) %>
    <h4>
      <%= @user.email %>
    </h4>

    <section>
      <%= render 'shared/stats' %>
    </section>
  <% if @user != current_user %>
      <%= render 'shared/follow_form' if signed_in? %>
  <% end %>
  <p></p>
</div>

<div class="left">
  <div class="span8 move-down-p">
    <% if @user.twits.any? %>
        <div class="panel panel-primary">
          <div class="panel-heading">Twit Feed (<%= @twits.count %>)</div>
          <ul>
            <%= render @twits %>
          </ul>
          <%= will_paginate @twits %>
        </div>
    <% end %>
  </div>
</div>
</div>